#!/usr/bin/env python3
"""
Aggregate PT boardings and alightings from MATSim events (PersonEntersVehicle / PersonLeavesVehicle).
PT vehicles are identified by vehicleId pattern (e.g. route_6_outbound_veh_0).
Output: CSV by route_id, direction, and hour for validation and dashboards.

Usage:
  python tools/analyse_pt_boardings_from_events.py <path-to-events.xml.gz> [--output <csv>]
  python tools/analyse_pt_boardings_from_events.py output/ITERS/it.10/10.events.xml.gz --output analysis-artifacts/pt-data/pt_boardings_alightings_by_route_hour.csv

Accepts: .xml or .xml.gz
"""

from __future__ import annotations

import argparse
import gzip
import re
import sys
from collections import defaultdict
from pathlib import Path


# PT vehicleId from PrepareShamalganTransitFromAssumptions: route_<routeId>_<outbound|inbound>_veh_<slot>
ROUTE_VEHICLE_PATTERN = re.compile(r"route_(\d+)_(outbound|inbound)_veh_\d+")

# Fallback: line_6_route_6_outbound_veh_0 (if generated by other tools)
LINE_ROUTE_PATTERN = re.compile(r"line_(\d+).*?route_[^_]+_(outbound|inbound)_veh_\d+")


def parse_vehicle_route(vehicle_id: str) -> tuple[str | None, str | None]:
    """Return (route_id, direction) or (None, None) if not a PT vehicle."""
    m = ROUTE_VEHICLE_PATTERN.search(vehicle_id)
    if m:
        return m.group(1), m.group(2)
    m = LINE_ROUTE_PATTERN.search(vehicle_id)
    if m:
        return m.group(1), m.group(2)
    # Generic PT vehicle (e.g. from GTFS): any id containing _veh_ and pt-like
    if "_veh_" in vehicle_id and ("route" in vehicle_id or "line" in vehicle_id.lower()):
        # Use full vehicle_id as route key if we can't parse
        return vehicle_id.split("_veh_")[0], "unknown"
    return None, None


def iter_events(events_path: Path):
    """Yield (event_type, time, attrs) from MATSim events XML. Events are usually one line each."""
    import xml.etree.ElementTree as ET
    open_fn = gzip.open if str(events_path).endswith(".gz") else open
    mode = "rt"
    with open_fn(events_path, mode, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("<event ") or "PersonEntersVehicle" not in line and "PersonLeavesVehicle" not in line:
                continue
            # MATSim writes: <event time="..." type="PersonEntersVehicle" person="..." vehicle="..."/>
            try:
                root = ET.fromstring(line)
            except ET.ParseError:
                # Fallback: regex
                import re
                tt = re.search(r'type="([^"]+)"', line)
                tm = re.search(r'time="([^"]+)"', line)
                vh = re.search(r'vehicle="([^"]+)"', line)
                if tt and tm and vh:
                    yield tt.group(1), float(tm.group(1)), {"vehicle": vh.group(1)}
                continue
            event_type = root.get("type")
            if event_type not in ("PersonEntersVehicle", "PersonLeavesVehicle"):
                continue
            try:
                time_sec = float(root.get("time", 0))
            except (TypeError, ValueError):
                time_sec = 0.0
            yield event_type, time_sec, {"vehicle": root.get("vehicle", "")}


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate PT boardings/alightings from MATSim events")
    parser.add_argument("events_file", type=Path, help="Path to events.xml or events.xml.gz")
    parser.add_argument("--output", "-o", type=Path, default=None, help="Output CSV path")
    args = parser.parse_args()

    if not args.events_file.exists():
        print(f"Error: file not found: {args.events_file}", file=sys.stderr)
        sys.exit(1)

    # (route_id, direction, hour) -> (boardings, alightings)
    counts = defaultdict(lambda: [0, 0])

    for event_type, time_sec, attrs in iter_events(args.events_file):
        if event_type not in ("PersonEntersVehicle", "PersonLeavesVehicle"):
            continue
        vehicle_id = attrs.get("vehicle", "")
        route_id, direction = parse_vehicle_route(vehicle_id)
        if route_id is None:
            continue
        hour = int(time_sec) // 3600
        key = (route_id, direction, hour)
        if event_type == "PersonEntersVehicle":
            counts[key][0] += 1
        else:
            counts[key][1] += 1

    out_path = args.output
    if out_path is None:
        out_path = args.events_file.parent / "pt_boardings_alightings_by_route_hour.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8", newline="") as f:
        f.write("route_id,direction,hour,boardings,alightings\n")
        for (route_id, direction, hour), (boardings, alightings) in sorted(counts.items()):
            f.write(f"{route_id},{direction},{hour},{boardings},{alightings}\n")

    print(f"Wrote {len(counts)} rows to {out_path}")


if __name__ == "__main__":
    main()
